#DEV environment

app:
  message: Este e o arquivo de propriedade ${spring.application.name} de desenvolvimento.

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa